name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  NODE_VERSION: '16.3'

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build Job
    steps:
      - uses: actions/checkout@v2

      # Setup Node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      # Restore Pacakges
      - run: npm ci

      # Build & Generate
      - run: npm run generate

      # move SWA config
      - name: move swa config
        run: mv staticwebapp.config.json ./dist

      # Upload Nuxt artifact
      - uses: actions/upload-artifact@v2
        with:
          name: nuxtdist
          path: dist

      # Upload Function App artifact
      - uses: actions/upload-artifact@v2
        with:
          name: functionapp
          path: api

  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Job
    steps:
      # Download Nuxt artifact
      - name: Download publish files
        uses: actions/download-artifact@v2
        with:
          name: nuxtdist
          path: dist

      # Download Function App artifact
      - name: Download function app
        uses: actions/download-artifact@v2
        with:
          name: functionapp
          path: api

      # Deploy to SWA
      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_FOREST_05A08F81E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: '/dist'
          api_location: '/api'
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_FOREST_05A08F81E }}
          action: 'close'
